""
"#version 120\r\n"
"uniform float fard;"
"uniform float neard;"
"uniform float fov;"
"uniform vec3 up;"
"uniform vec3 right;"
"uniform vec3 view;"
"uniform vec3 pos;"
"uniform float width;"
"uniform float height;"
"varying vec3 ip;"
"uniform vec3 partp[4];"
"uniform float partq[4];"
"uniform float partm[4];"
"void main()"
"{"
"	ip = gl_Vertex.xyz;"
"	gl_Position = gl_Vertex * vec4(2,2,2,1) - vec4(1,1,1,0);//*vec4(1/width,1/height,2,1) - vec4(1,1,1,0);\r\n"
"	//gl_Position = vec4(toxy(gl_Vertex.xyz, width, height, view, pos, up, right, fard, neard, fov), 1);\r\n"
"}"