""
"#version 120\r\n"
"uniform float fard;"
"uniform float neard;"
"uniform float width;"
"uniform float height;"
"uniform vec4 view;"
"uniform vec4 pos;"
"\r\n"
"void main()"
"{"
"	float extx = 2.2 * width / height / 2.0;"
"	float exty = 2.2 / 2.0f;"
"	gl_Position = vec4("
"	(gl_Vertex.w - view.w + extx / 2.0) / extx * 2.0 - 1.0,"
"	(gl_Vertex.y - view.y + exty / 2.0) / exty * 2.0 - 1.0,"
"	(gl_Vertex.x - pos.x + neard) / (fard-neard) * 2.0 - 1.0,"
"	1);\r\n"
"}"